# Python config
python3.bin=python3

# PostgreSQL config
pg.db=test

# Experiment config
common.experiment.repeat=1
common.experiment.timeout=60

# Parser config (SparkSQL Plus)
parser.mode=local
parser.hdfs.host=localhost
parser.hdfs.port=50070
parser.hdfs.user=sqlplus

